---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: print out the hostname of target
      command: hostname
    - name: get uptime
      command: uptime
    - name: install nginx via amazon extras
      command: amazon-linux-extras install nginx1.12 -y
    - name: start nginx
      service:
        name: nginx
        state: started
